/**
 * GENERATED by scripts/build-assets.mjs — do not edit by hand.
 * Run `pnpm logos && pnpm assets` to refresh.
 *
 * Every project mark that exists as a real asset. A `light`/`dark` pair means
 * the source carried a prefers-color-scheme rule and was split so the site's
 * own theme toggle drives it; `src` means one file serves both themes.
 *
 * Projects absent from this map fall back to the drawn glyph in marks.ts.
 */

export type Logo = { src: string } | { light: string; dark: string };

export const logos: Record<string, Logo> = {
  "aeperion": {
    "light": "/logos/aeperion-light.svg",
    "dark": "/logos/aeperion-dark.svg"
  },
  "aimperion": {
    "light": "/logos/aimperion-light.svg",
    "dark": "/logos/aimperion-dark.svg"
  },
  "chudopoly": {
    "src": "/logos/chudopoly.svg"
  },
  "coup": {
    "src": "/logos/coup.webp"
  },
  "hatchdle": {
    "src": "/logos/hatchdle.webp"
  },
  "imprimatur": {
    "src": "/logos/imprimatur.webp"
  },
  "instagib-arena": {
    "src": "/logos/instagib-arena.svg"
  },
  "mouserank": {
    "src": "/logos/mouserank.svg"
  },
  "palhelm": {
    "src": "/logos/palhelm.svg"
  },
  "startpage": {
    "light": "/logos/startpage-light.svg",
    "dark": "/logos/startpage-dark.svg"
  },
  "vitals": {
    "src": "/logos/vitals.svg"
  }
};

export const logoFor = (slug: string): Logo | null => logos[slug] ?? null;

export const isThemed = (logo: Logo): logo is { light: string; dark: string } =>
  "light" in logo;
