/**
 * Single source of truth for identity, domain and contact.
 *
 * Swapping domain or email is an edit to `url` and `email` here — canonical
 * links, Open Graph URLs, robots.txt and the sitemap all read from this file
 * (`astro.config.ts` imports `site.url`).
 *
 * The one other place a hostname is written down is `public/CNAME`, which is
 * the GitHub Pages DNS target rather than site config. Update it too if you
 * deploy there.
 */
export const site = {
  /** Swap when a name-forward domain is registered. Keep the protocol, no trailing slash. */
  url: "https://8tp.dev",

  /** Human name is the brand. `8tp` stays a GitHub handle, not a logo. */
  title: "Hunter M.",
  role: "Software engineer",

  /** Used in the <title> tag and OG title. Just the name — the tab stays quiet. */
  seoTitle: "Hunter M.",

  /** Hero thesis. One line, specific, no hype. Also the JSON-LD description. */
  tagline: "I design and build websites and web apps for clients, and make games and tools of my own.",

  description:
    "Hunter M. designs and builds storefronts, product sites and web apps for clients, plus browser games, self-hosted tools and Mac apps of his own.",

  /**
   * The availability line under the intro. Keep it true; set to null to hide
   * it rather than leave something stale up. `updated` prints in the footer so
   * a reader can tell how fresh it is.
   */
  availability: "I'm taking on client work now. Email is the quickest way to reach me." as string | null,
  updated: "October 2026",

  /**
   * Page backdrop: a shader from src/lib/backdrops.ts ("contours", "window",
   * "paper", "marbling", "guilloche"), or "dither" / "none".
   * Any of them can be previewed with ?bg=<name> on the URL.
   */
  backdrop: "contours" as string,

  /** Placeholder until a domain is locked; forward this address to the new inbox. */
  email: "hunter@8tp.dev",

  author: {
    name: "Hunter M.",
    firstName: "Hunter",
    /** GitHub handle only — not a site brand. */
    handle: "8tp",
    location: "USA",
    /**
     * Optional portrait. Drop a square image at `public/avatar.jpg` (1024x1024
     * master, see docs/redesign/04-profile-image.md) and set this to
     * "/avatar.jpg" to switch the hero to its portrait layout.
     */
    avatar: null as string | null,
  },

  socials: [{ label: "GitHub", handle: "@8tp", url: "https://github.com/8tp" }],

  /** 1200x630, regenerated by `pnpm assets`. */
  og: {
    image: "/og.png",
    width: 1200,
    height: 630,
    alt: "Hunter M., set in serif on dithered paper",
  },

  /** Matches --paper in src/styles/global.css for each theme. */
  themeColor: { light: "#f6f6f3", dark: "#101411" },
};

export type Site = typeof site;
